### ISSUE TITLE
最新一次提交打卡功能异常

### ISSUE THREAD

**Issue by hhhllll888** [CarltonHere/auto-cpdaily#32]
隐私字段用‘xxxxxxxx’代替了
```log
START RequestId: 3a0eb85a-38db-4d34-a604-2b75a7604499

Init Report RequestId: 3a0eb85a-38db-4d34-a604-2b75a7604499 Coldstart: 3321ms (PullCode: 281ms InitRuntime: 7ms InitFunction: 3033ms) Memory: 128MB MemUsage: 35.18MB

2022-03-20 00:20:18 V1.8.5 自动化任务开始执行

2022-03-20 00:20:18 V1.8.5 10s后开始执行用户2021104230238的任务

2022-03-20 00:20:28 V1.8.5 正在获取登录地址

2022-03-20 00:20:28 V1.8.5 开始尝试登录账号

Starting new HTTPS connection (1): mobile.campushoy.com:443

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=2f11300e-568c-49b0-9096-7c5543c81d75 HTTP/1.1" 200 None

Starting new HTTPS connection (1): xxxx.campusphere.net:443

https://xxxx.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 301 178

https://xxxx.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 302 154

https://xxxx.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Fxxxx.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 302 0

https://xxxx.campusphere.net:443 "GET /iap/login/mobile.html?_2lBepC=d4afd187742a406487f733dec67c0ad9 HTTP/1.1" 200 1708

https://xxxx.campusphere.net:443 "POST /iap/security/lt HTTP/1.1" 200 None

https://xxxx.campusphere.net:443 "POST /iap/checkNeedCaptcha?username=20211xxxxxxxx HTTP/1.1" 200 None

https://xxxx.campusphere.net:443 "POST /iap/doLogin?lt=aa3bb20772fe4c5f843b7ac8c3b47701&rememberMe=false&dllt=&mobile=&username=20211xxxxxxxx&password=xxxxxxxx&captcha= HTTP/1.1" 302 0

https://xxxx.campusphere.net:443 "POST /portal/login HTTP/1.1" 302 154

https://xxxx.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Fxxxx.campusphere.net%2Fportal%2Flogin HTTP/1.1" 302 0

https://xxxx.campusphere.net:443 "GET /portal/login?ticket=ST-iap:1020393983924721:ST:3af9b195-f0b8-47bb-8100-98a2becc255c:20220320002029 HTTP/1.1" 302 154

https://xxxx.campusphere.net:443 "GET /portal/login HTTP/1.1" 302 0

https://xxxx.campusphere.net:443 "GET /portal/index.html HTTP/1.1" 200 68189

2022-03-20 00:20:30 V1.8.5 开始执行收集任务

https://xxxx.campusphere.net:443 "POST /wec-counselor-collector-apps/stu/collector/queryCollectorProcessingList HTTP/1.1" 200 None

https://xxxx.campusphere.net:443 "POST /wec-counselor-collector-apps/stu/collector/detailCollector HTTP/1.1" 200 None

https://xxxx.campusphere.net:443 "POST /wec-counselor-collector-apps/stu/collector/getFormFields HTTP/1.1" 200 None

2022-03-20 00:20:31 V1.8.5 正在加密表单数据

2022-03-20 00:20:31 V1.8.5 正在尝试提交数据

https://xxxx.campusphere.net:443 "POST /wec-counselor-collector-apps/stu/collector/submitForm HTTP/1.1" 200 None

2022-03-20 00:20:32 V1.8.5 信息收集提交异常

Applying Foxmail.com Defaults

Loaded E-Mail URL: mailtos://xxxxxxxxx:****@qq.com/xxxxxxxxx%40qq.com?from=xxxxxxxxx%40qq.com&mode=starttls&smtp=smtp.qq.com&user=xxxxxxxxx%40qq.com&format=html&overflow=upstream&rto=4.0&cto=15&verify=yes

Using selector: EpollSelector

Notifying 1 service(s) asynchronously.

Email From: Apprise Notifications <xxxxxx@qq.com>

Email To: xxxxxxxx@qq.com

Login ID: xxxxxxx@qq.com

Delivery: smtp.qq.com:587

Connecting to remote SMTP server...

Securing connection with STARTTLS...

Applying user credentials...

Sent Email notification to "xxxxx@qq.com".

2022-03-20 00:20:32 V1.8.5 APPRISE推送消息成功

2022-03-20 00:20:32 V1.8.5 自动化任务执行完毕

Response RequestId:3a0eb85a-38db-4d34-a604-2b75a7604499 RetMsg:"Finished"

END RequestId:3a0eb85a-38db-4d34-a604-2b75a7604499

Report RequestId:3a0eb85a-38db-4d34-a604-2b75a7604499 Duration:14846ms Memory:128MB MemUsage:43.957031MB 
```
推送功能正常，提交yml为
```yml
###############################################################################
# 本项目的源代码在MPL2.0协议下发布，同时附加以下条目：                            #
# 非商业性使用 — 不得将此项目及其衍生的项目的源代码和二进制产品用于任何商业和盈利用途#
###############################################################################
# 调试模式，用于寻找错误出现的坐标，默认为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
debug: false
# 消息推送配置，method 0 为禁用 1 为webApi模式 2 为APPRISE模式，请参考https://github.com/caronc/apprise/wiki
notifyOption:
    method: 2
    #############1 webApi配置,根据不同api可能需要自行修改推送模块
    mailApiUrl: 'http://api.ruoli.cc/mail/sendMail'
# 默认不填，如需使用先开通腾讯云OCR服务，再申请API密钥
ocrOption:
    SecretId: 'APIid'
    SecretKey: 'APIkey'
# 如IP被拦截，可设置全局HTTP代理
httpProxy: ''
#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
    # 第一个用户配置
    # 以下配置为工作日志
    # 这里默认仅适配宜宾学院，其他学校自行修改
    - user:
        # 任务类型（收集：0、签到：1、查寝：2、政工签到：3、教师工作日志：4）
        type: 0
        # school 学校全称
        schoolName: xxxx学院
        # username 学号或者工号
        username: 'xxxxxxx'
        # password 密码
        password: 'xxxxxx'
        # 地址信息
        address: '中国安徽省滁州市'
        notifyOption: 
            # method和顶部参数一致，不填默认按照顶部参数执行
            # method: 0
            # rcvOption为接受消息的配置，method为1时直接填写邮箱即可，method为2时请参考
            # https://github.com/caronc/apprise/wiki进行配置
            # 示例1 'mailto://邮箱账号:邮箱密码@邮箱名.com' --- 'mailto://账号:密码@163.com'
            # 示例2 'mailto://发信邮箱账号:发信邮箱密码@发信邮箱名.com/?to=收信人邮箱'  --- 'mailto://账号:密码@163.com/to=收信邮箱@qq.com'
            # 注意！！！一部分邮箱（如163邮箱）需要在设置中申请smtp授权码，此处的邮箱密码填写授权码
            rcvOption: 'mailto://xxxxxxx:xxxxxxx@qq.com/?to=xxxxxxx@qq.com'
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        # lon 经度
        lon: 118.308735
        # lat 纬度
        lat: 32.25387
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        # 是否只填必填项
        onlyRequired: 1
        # 表单信息
        forms:
            - form: #1
                title: 你的健康状态
                value: 健康
            - form: #2 x
                title: 如有发热、感冒、咳嗽、呼吸困难等症状，是否做了核酸检测及检测结果为 (如无相关症状的不填)
                ignore: True
            - form: #3 
                title: 你当前是否被隔离
                value: 否
            - form: #4 x
                title: 如果被隔离，填写目前被隔离的地址
                ignore: True
            - form: #5
                title: 你目前是否在校 (必填)
                value: 是
            - form: #6（在校取消678，将5设置成是）
                title: 如你不在校，你目前所在城市为(在校的不填)
                ignore: True
            - form: #7
                title: 如你目前不在校，你是否确定了返回学校的时间 (在校的不填)
                value: 未确定
                ignore: True
            - form: #8 x
                title: 如果已确定，请选择你的返回时间（未确定的不填）
                ignore: True
            - form: #9
                title: 近一个月，你是否有境外地区或疫情中高风险地区旅居史（中高风险地区以官方发布为准）
                value: 否
            - form: #10 x
                title: 什么时间旅居何地（中高风险地区以官方发布为准）
                ignore: True
            - form: #11
                title: 近一个月，你是否与确诊人员或中高风险地区、境外入境人员密切接触
                value: 否
            - form: #12 x
                title: 如果有密切接触、境外地区或疫情中高风险地区旅居史，是否做过核酸检测及检测结果为（没有接触的不填）
                ignore: True
    # 第二个用户配置
    # 以下配置为信息收集
    # 这里默认仅适配宜宾学院，其他学校自行修改
```
