### ISSUE TITLE
信息收集提交异常

### ISSUE THREAD

**Issue by Maxmumu** [CarltonHere/auto-cpdaily#57]
```
- user:
        # 任务类型（收集：0、签到：1、查寝2）
        type: 0
        # 学校名称
        schoolName: ''
        # 账号
        username: ''
        # 密码
        password: ''
        # 定位位置信息
        address: ''
        notifyOption: 
            # method和顶部参数一致，不填默认按照顶部参数执行
            # method: 0
            # rcvOption为接受消息的配置，method为1时直接填写邮箱即可，method为2时请参考
            # https://github.com/caronc/apprise/wiki进行配置
            # 示例1 规则: 'mailto://邮箱账号:邮箱密码@邮箱名.com' 示范: 'mailto://账号:密码@163.com'
            # 示例2 规则: 'mailto://发信邮箱账号:发信邮箱密码@发信邮箱名.com/?to=收信人邮箱' 示范: 'mailto://账号:密码@163.com/?to=收信邮箱@qq.com'
            # 注意！！！一部分邮箱（如163邮箱）需要在设置中申请smtp授权码，此处的邮箱密码填写授权码
            # 账号是邮箱@符号前的部分，比如admin@163.com的用户名就是admin
            rcvOption: 'mailto://账号:密码@163.com'
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        # lon 经度
        lon: 
        # 经纬度信息
        lat: 
        # 可以指定签到任务
        # formTitle: "学生疫情防控情况每日排查"
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        # 是否只填必填项
        onlyRequired: 1
        # 表单信息
        forms:
            ……………………
            - form: #6
                  title: 校外居住地址
                  ignore: True
            - form: #7
                  title: 当前该乡镇街道是否有封控（管制）区
                  ignore: True
            - form: #8
                  title: 你今日是否被界定为确诊、疑似、无症状感染者、密接人员、次密接人员或一般接触人员。
                  value: 没有被界定为以上新冠重点关注人员
            - form: #9
                  title: 隔离或留观开始时间
                  ignore: True
            - form: #10
                  title: 隔离或留观地点
                  ignore: True
            - form: #11
                  title: 接种新冠疫苗情况
                  value: 未接种新冠疫苗
            - form: #12
                  title: 今日核酸检测情况
                  value: 今日已做核酸，结果未出
            - form: #13
                  title: 近14天内是否有昆明市以外地区旅居史
                  value: 否
            - form: #14
                  title: 近14天内昆明市以外地区旅居地址
                  ignore: True
            - form: #15
                  title: 今日云南健康码是否异常
                  value: 无异常
            - form: #16
                  title: 今日属地健康码是否异常
                  ignore: True
            - form: #17
                  title: 请上传你的健康码和行程码
                  value:
                        - './sign.jpg'
            - form: #18
                  title: 当日是否有新冠肺炎相关“十大症状”（发热、干咳、乏力、嗅味觉减退、鼻塞、流涕、咽痛、结膜炎、肌痛、腹泻等）
                  value: 无
            - form: #19
                  title: 当日是否因“十大症状”缺勤、缺课或请假
                  value: 否
            - form: #20
                  title: 今日是否收到疾控部门预警电话或短信
                  value: 未收到任何疾控部门的短信或电话
            #- form: #21
            #      title: 接到短信或电话后，是否已报告学校
            #      value: ''
            #      ignore: True
            - form: #22
                  title: 本人承诺以上所填信息真实有效，若有谎报、瞒报情况，愿承担相应的法律责任，接受学校相应的校纪校规处分
                  value:
                    - './sign.jpg'
```

**22题为手写签名，按照上面的方式提交，结果“提交异常”。**
![image](https://user-images.githubusercontent.com/47938014/176818417-bb7716e1-dffd-4e87-b8b8-408598fa3cac.png)
